;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[bar/bar-top]
width = 100%
height = 20pt

background = #00000000
foreground = #C5C8C6

module-margin = 1

padding-right = 1

separator = |
separator-foreground = #707880

font-0 = "FiraCode Nerd Font:size=10;2"
font-1 = "Material Design Icons Desktop:size=14;2"
font-2 = "FiraCode Nerd Font:size=8;2"

label-active-font = 1

modules-left = workspaces xwindow
modules-right = redshift backlight pulseaudio xkeyboard memory cpu temperature system-bluetooth-bluetoothctl wlan eth date

cursor-click = pointer
cursor-scroll = 

enable-ipc = true

[module/system-bluetooth-bluetoothctl]
type = custom/script
exec = $HOME/.config/polybar/scripts/system-bluetooth-bluetoothctl.sh
tail = true
click-left = $HOME/.config/polybar/scripts/system-bluetooth-bluetoothctl.sh --toggle &
interval = 1
format = %{A3:blueman-manager:}<label>%{A}
label = %output%

[module/system-gpu-optimus]
type = custom/script
exec = $HOME/.config/polybar/scripts/system-gpu-optimus.sh
interval = 1200
format = <label>
label = %{F#ed80a8}%{T2}󰢮%{T-}%{F-} %output%

[module/redshift]
type = custom/script
exec = source ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift.sh temperature 
click-left = source ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift.sh toggle 
scroll-up = source ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift.sh increase
scroll-down = source ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift.sh decrease
interval=1

format = <label>
label = %output%

[module/workspaces]
type = internal/i3
show-urgent = true

ws-icon-0 = 1;󰲡
ws-icon-1 = 2;󰲣
ws-icon-2 = 3;󰲥
ws-icon-3 = 4;󰲧
ws-icon-4 = 5;󰲩
ws-icon-5 = 6;󰲫
ws-icon-6 = 7;󰲭
ws-icon-7 = 8;󰲯
ws-icon-8 = 9;󰲱
ws-icon-9 = 10;󰿭

format = <label-state> <label-mode>

label-focused = %{T2}%icon%%{T-}
label-focused-foreground = #ed80a8
label-focused-padding = 0

label-unfocused = %{T2}%icon%%{T-}
label-unfocused-padding = 0

label-urgent = %name%
label-urgent-foreground = #ffffff
label-urgent-background = #e3256b
label-urgent-padding = 1

[module/xwindow]
type = internal/xwindow

format = <label>
format-padding = 0
label = %{T3}%title:0:40:..%%{T-}
; label-maxlen = 40

[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
enable-scroll = false

format = %{A4:brightnessctl s 10%+:}%{A5:brightnessctl s 10%-:}%{F#ed80a8}<ramp>%{F-} <label>%{A}%{A}
label = %percentage%%

ramp-0 = %{T2}󱩏%{T-}
ramp-1 = %{T2}󱩑%{T-}
ramp-2 = %{T2}󱩓%{T-}
ramp-3 = %{T2}󱩕%{T-}
ramp-4 = %{T2}󰛨%{T-}

[module/pulseaudio]
type = internal/pulseaudio
interval = 2
use-ui-max = true

format-volume = %{F#ed80a8}<ramp-volume>%{F-} <label-volume>
label-volume = %percentage%%

label-muted = %{F#ed80a8}%{T2}󰝟%{T-}%{F-}

ramp-volume-0 = %{T2}󰕿%{T-}
ramp-volume-1 = %{T2}󰖀%{T-}
ramp-volume-2 = %{T2}󰕾%{T-}

click-right = pavucontrol

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = scroll lock

format = <label-layout>%{T2}󰧟%{T-}<label-indicator>
label-layout = %layout%

label-indicator-on = %icon%
label-indicator-off = %icon%

indicator-icon-0 = caps lock;%{T2}󰬵%{T-};%{F#ed80a8}%{T2}󰬶%{T-}%{F-}
indicator-icon-1 = num lock;%{T2}󰧟%{T-}%{T2}󱧓%{T-};%{T2}󰧟%{T-}%{F#ed80a8}%{T2}󰎠%{T-}%{F-}

[module/memory]
type = internal/memory
interval = 2
warn-percentage = 80

format = %{A1:kitty htop:}<label> <ramp-used>%{A}
label = %{F#ed80a8}%{T2}󰘚%{T-}%{F-}%percentage_used:2%%%{T2}󰧟%{T-}%used%

format-warn = %{A1:kitty htop:}%{F#e3256b}<label-warn> <ramp-used>%{F-}%{A}
label-warn = %{T2}󰘚%{T-}%percentage_used:2%%%{T2}󰧟%{T-}%used%

ramp-used-0 = ▁
ramp-used-1 = ▂
ramp-used-2 = ▃
ramp-used-3 = ▄
ramp-used-4 = ▅
ramp-used-5 = ▆
ramp-used-6 = ▇
ramp-used-7 = █

[module/cpu]
type = internal/cpu
interval = 1
warn-percentage = 80

format = %{A1:kitty htop:}<label> <ramp-coreload>%{A}
label = %{F#ed80a8}%{T2}󰍛%{T-}%{F-}%percentage:2%%

format-warn = %{A1:kitty htop:}%{F#e3256b}<label-warn> <ramp-coreload>%{F-}%{A}
label-warn = %{T2}󰍛%{T-}%percentage:2%%

ramp-coreload-spacing = 0
ramp-coreload-0 = ▁
ramp-coreload-1 = ▂
ramp-coreload-2 = ▃
ramp-coreload-3 = ▄
ramp-coreload-4 = ▅
ramp-coreload-5 = ▆
ramp-coreload-6 = ▇
ramp-coreload-7 = █

[module/temperature]
type = internal/temperature
interval = 1
base-temperature = 20
warn-temperature = 80
units = true

format = <label>
label = %{F#ed80a8}%{T2}󰔏%{T-}%{F-}%temperature-c%

format-warn = %{F#e3256b}<label-warn>%{F-}
label-warn = %{T2}󰔏%{T-}%temperature-c%

[network-base]
type = internal/network
interval = 1

format-disconnected = <label-disconnected>
label-disconnected = 

[module/wlan]
inherit = network-base
interface-type = wireless

format-connected = %{A1:kitty nmtui:}<ramp-signal> <label-connected>%{A}
label-connected = %{F#ed80a8}%{T2}󰄼%{T-}%{F-}%downspeed%
ramp-signal-0 = %{F#ed80a8}%{T2}󰤯%{T-}%{F-}
ramp-signal-1 = %{F#ed80a8}%{T2}󰤟%{T-}%{F-}
ramp-signal-2 = %{F#ed80a8}%{T2}󰤟%{T-}%{F-}
ramp-signal-3 = %{F#ed80a8}%{T2}󰤢%{T-}%{F-}
ramp-signal-4 = %{F#ed80a8}%{T2}󰤥%{T-}%{F-}
ramp-signal-5 = %{F#ed80a8}%{T2}󰤨%{T-}%{F-}


[module/eth]
inherit = network-base
interface-type = wired
unknown-as-up = true

format-connected = %{A1:kitty nmtui:}<label-connected>%{A}
label-connected = %{F#ed80a8}%{T2}󰈀%{T-}%{F-} %{F#ed80a8}%{T2}󰄼%{T-}%{F-}%downspeed%%{T2}󰧟%{T-}%linkspeed%

[module/date]
type = internal/date
interval = 1

date = %{F#ed80a8}%{T2}󱑒%{T-}%{F-} %H:%M:%S

label = %{A:$HOME/.config/polybar/scripts/calendar.sh --popup &:}%date%%{A}

[settings]
screenchange-reload = true
pseudo-transparency = true